version: '3.8'
services:
  api:
    build: .
    container_name: frontend
    restart: always  
    ports:
      - "80:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
